"""Add many-to-many relationship between Parcours and Niveau

Revision ID: 10e7d2940333
Revises: 85211e3a91f2
Create Date: 2025-09-30 23:37:24.850757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10e7d2940333'
down_revision = '85211e3a91f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcours_niveaux',
    sa.Column('parcours_id', sa.Integer(), nullable=False),
    sa.Column('niveau_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['niveau_id'], ['niveaux.id'], ),
    sa.ForeignKeyConstraint(['parcours_id'], ['parcours.id'], ),
    sa.PrimaryKeyConstraint('parcours_id', 'niveau_id')
    )
    with op.batch_alter_table('parcours', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('parcours_niveau_id_fkey'), type_='foreignkey')
        batch_op.drop_column('niveau_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('niveau_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('parcours_niveau_id_fkey'), 'niveaux', ['niveau_id'], ['id'])

    op.drop_table('parcours_niveaux')
    # ### end Alembic commands ###
