"""add departement and est_actif to admin

Revision ID: 151324149523
Revises: 726ad24e391c
Create Date: 2025-10-28 13:40:42.142880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '151324149523'
down_revision = '726ad24e391c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departement', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('est_actif', sa.Boolean(), nullable=True))

    with op.batch_alter_table('etudiant', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['utilisateur_id'])

    with op.batch_alter_table('qcms', schema=None) as batch_op:
        batch_op.alter_column('document_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('resultats', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'etudiant', ['etudiant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resultats', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('qcms', schema=None) as batch_op:
        batch_op.alter_column('document_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('etudiant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('est_actif')
        batch_op.drop_column('departement')

    # ### end Alembic commands ###
