"""refactor_mentions_remove_specialites_add_mention_to_parcours

Revision ID: 2b88cd8ea016
Revises: 6ce8fb94ac57
Create Date: 2025-09-30 21:27:28.328550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b88cd8ea016'
down_revision = '6ce8fb94ac57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Supprimer d'abord la contrainte de clé étrangère
    with op.batch_alter_table('etudiant', schema=None) as batch_op:
        batch_op.drop_constraint('etudiant_specialite_id_fkey', type_='foreignkey')
        batch_op.drop_column('specialite_id')

    # Supprimer la table specialite
    op.drop_table('specialite')

    # Ajouter mention_id aux parcours
    with op.batch_alter_table('parcours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mention_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'mention', ['mention_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcours', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('mention_id')

    with op.batch_alter_table('etudiant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialite_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('etudiant_specialite_id_fkey'), 'specialite', ['specialite_id'], ['id'])

    op.create_table('specialite',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('mention_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('est_actif', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['mention_id'], ['mention.id'], name=op.f('specialite_mention_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('specialite_pkey'))
    )
    # ### end Alembic commands ###
