"""Add est_actif field to etudiant and enseignant models

Revision ID: 2eb46d62b200
Revises: b049c29b8cba
Create Date: 2025-09-18 20:29:49.593979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eb46d62b200'
down_revision = 'b049c29b8cba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enseignant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('est_actif', sa.Boolean(), nullable=True))

    with op.batch_alter_table('etudiant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('est_actif', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etudiant', schema=None) as batch_op:
        batch_op.drop_column('est_actif')

    with op.batch_alter_table('enseignant', schema=None) as batch_op:
        batch_op.drop_column('est_actif')

    # ### end Alembic commands ###
