"""Refactor QCM model

Revision ID: 5838e14fc7ae
Revises: 80abb1e54c0c
Create Date: 2025-09-15 09:31:42.124744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5838e14fc7ae'
down_revision = '80abb1e54c0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texte', sa.Text(), nullable=False),
    sa.Column('qcm_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['qcm_id'], ['qcms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('options_reponse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('options_reponse_qcm_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'questions', ['question_id'], ['id'])
        batch_op.drop_column('qcm_id')

    with op.batch_alter_table('qcms', schema=None) as batch_op:
        batch_op.drop_column('contenu')
        batch_op.drop_column('reponse_attendue')

    with op.batch_alter_table('resultats', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('resultats_etudiant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'etudiant', ['etudiant_id'], ['utilisateur_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resultats', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('resultats_etudiant_id_fkey'), 'utilisateur', ['etudiant_id'], ['id'])

    with op.batch_alter_table('qcms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reponse_attendue', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('contenu', sa.TEXT(), autoincrement=False, nullable=False))

    with op.batch_alter_table('options_reponse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qcm_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('options_reponse_qcm_id_fkey'), 'qcms', ['qcm_id'], ['id'])
        batch_op.drop_column('question_id')

    op.drop_table('questions')
    # ### end Alembic commands ###
