"""add_mention_and_specialite_tables

Revision ID: 6ce8fb94ac57
Revises: 9f8e2a1b3c4d
Create Date: 2025-09-30 21:15:59.809262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ce8fb94ac57'
down_revision = '9f8e2a1b3c4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mention',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('est_actif', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('specialite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('mention_id', sa.Integer(), nullable=False),
    sa.Column('est_actif', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['mention_id'], ['mention.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('etudiant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mention_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('specialite_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'mention', ['mention_id'], ['id'])
        batch_op.create_foreign_key(None, 'specialite', ['specialite_id'], ['id'])

    with op.batch_alter_table('qcms', schema=None) as batch_op:
        batch_op.alter_column('est_cible',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.drop_index(batch_op.f('ix_qcms_est_cible'))
        batch_op.drop_index(batch_op.f('ix_qcms_matiere_id'))
        batch_op.drop_index(batch_op.f('ix_qcms_niveau_id'))
        batch_op.drop_index(batch_op.f('ix_qcms_parcours_id'))
        batch_op.create_foreign_key(None, 'matieres', ['matiere_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qcms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_qcms_parcours_id'), ['parcours_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qcms_niveau_id'), ['niveau_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qcms_matiere_id'), ['matiere_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qcms_est_cible'), ['est_cible'], unique=False)
        batch_op.alter_column('est_cible',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('etudiant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('specialite_id')
        batch_op.drop_column('mention_id')

    op.drop_table('specialite')
    op.drop_table('mention')
    # ### end Alembic commands ###
