"""Initial migration

Revision ID: 80abb1e54c0c
Revises: 
Create Date: 2025-09-01 20:34:47.344994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80abb1e54c0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('utilisateur_id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('enseignant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['enseignant_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enseignant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('matiere', sa.String(length=120), nullable=True),
    sa.Column('departement', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('utilisateur_id')
    )
    op.create_table('etudiant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('matriculeId', sa.String(length=50), nullable=False),
    sa.Column('niveau', sa.String(length=50), nullable=True),
    sa.Column('parcours', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matriculeId'),
    sa.UniqueConstraint('utilisateur_id')
    )
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duree_limite', sa.Integer(), nullable=True),
    sa.Column('nombre_questions', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_limite', sa.DateTime(), nullable=True),
    sa.Column('est_active', sa.Boolean(), nullable=True),
    sa.Column('enseignant_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['enseignant_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qcms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('type_exercice', sa.Enum('QCM', 'VRAI_FAUX', 'QUESTION_OUVERTE', name='typeexercice'), nullable=False),
    sa.Column('difficulte', sa.Enum('FACILE', 'MOYEN', 'DIFFICILE', name='difficulte'), nullable=False),
    sa.Column('reponse_attendue', sa.Text(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('options_reponse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texte', sa.Text(), nullable=False),
    sa.Column('est_correcte', sa.Boolean(), nullable=True),
    sa.Column('qcm_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['qcm_id'], ['qcms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reponses_composees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('date_soumission', sa.DateTime(), nullable=True),
    sa.Column('temps_execution', sa.Integer(), nullable=True),
    sa.Column('est_correcte', sa.Boolean(), nullable=True),
    sa.Column('etudiant_id', sa.Integer(), nullable=False),
    sa.Column('qcm_id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['etudiant_id'], ['utilisateur.id'], ),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.ForeignKeyConstraint(['qcm_id'], ['qcms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resultats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Float(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('date_correction', sa.DateTime(), nullable=True),
    sa.Column('temps_total', sa.Integer(), nullable=True),
    sa.Column('nombre_correctes', sa.Integer(), nullable=True),
    sa.Column('nombre_incorrectes', sa.Integer(), nullable=True),
    sa.Column('pourcentage', sa.Float(), nullable=True),
    sa.Column('etudiant_id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etudiant_id'], ['utilisateur.id'], ),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultats')
    op.drop_table('reponses_composees')
    op.drop_table('options_reponse')
    op.drop_table('qcms')
    op.drop_table('evaluations')
    op.drop_table('etudiant')
    op.drop_table('enseignant')
    op.drop_table('documents')
    op.drop_table('admin')
    op.drop_table('utilisateur')
    # ### end Alembic commands ###
