"""add_niveau_id_to_parcours

Revision ID: 85211e3a91f2
Revises: 2b88cd8ea016
Create Date: 2025-09-30 22:40:55.814831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85211e3a91f2'
down_revision = '2b88cd8ea016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('niveau_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'niveaux', ['niveau_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcours', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('niveau_id')

    # ### end Alembic commands ###
