"""Remove old matiere field from enseignant model

Revision ID: a14721653a5c
Revises: be6ad8a2e781
Create Date: 2025-09-18 21:48:09.534685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a14721653a5c'
down_revision = 'be6ad8a2e781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enseignant', schema=None) as batch_op:
        batch_op.drop_column('matiere')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enseignant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matiere', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
