"""Add niveaux and parcours tables, update etudiant model

Revision ID: b049c29b8cba
Revises: 5838e14fc7ae
Create Date: 2025-09-18 18:40:36.908816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b049c29b8cba'
down_revision = '5838e14fc7ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('niveaux',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.Column('est_actif', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('parcours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('est_actif', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('etudiant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('niveau_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('parcours_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'niveaux', ['niveau_id'], ['id'])
        batch_op.create_foreign_key(None, 'parcours', ['parcours_id'], ['id'])
        batch_op.drop_column('parcours')
        batch_op.drop_column('niveau')

    with op.batch_alter_table('resultats', schema=None) as batch_op:
        batch_op.alter_column('qcm_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resultats', schema=None) as batch_op:
        batch_op.alter_column('qcm_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('etudiant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('niveau', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('parcours', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parcours_id')
        batch_op.drop_column('niveau_id')

    op.drop_table('parcours')
    op.drop_table('niveaux')
    # ### end Alembic commands ###
