"""Add annee_universitaire field to Etudiant

Revision ID: bacf32229d66
Revises: 10e7d2940333
Create Date: 2025-10-05 23:52:08.543110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bacf32229d66'
down_revision = '10e7d2940333'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # D'abord ajouter la colonne comme nullable
    with op.batch_alter_table('etudiant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('annee_universitaire', sa.String(length=20), nullable=True))
    
    # Mettre à jour les valeurs existantes
    op.execute("UPDATE etudiant SET annee_universitaire = '2024-2025' WHERE annee_universitaire IS NULL")
    
    # Maintenant rendre la colonne NOT NULL
    with op.batch_alter_table('etudiant', schema=None) as batch_op:
        batch_op.alter_column('annee_universitaire', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etudiant', schema=None) as batch_op:
        batch_op.drop_column('annee_universitaire')

    # ### end Alembic commands ###
