"""Refactor matieres: remove niveau/parcours, add advanced assignment table

Revision ID: be6ad8a2e781
Revises: c33073617548
Create Date: 2025-09-18 21:28:02.842352

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be6ad8a2e781'
down_revision = 'c33073617548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matiere_enseignant_niveau_parcours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matiere_id', sa.Integer(), nullable=False),
    sa.Column('enseignant_id', sa.Integer(), nullable=False),
    sa.Column('niveau_id', sa.Integer(), nullable=True),
    sa.Column('parcours_id', sa.Integer(), nullable=True),
    sa.Column('est_actif', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['enseignant_id'], ['enseignant.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.ForeignKeyConstraint(['niveau_id'], ['niveaux.id'], ),
    sa.ForeignKeyConstraint(['parcours_id'], ['parcours.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('matiere_enseignant')
    with op.batch_alter_table('matieres', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('matieres_niveau_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('matieres_parcours_id_fkey'), type_='foreignkey')
        batch_op.drop_column('parcours_id')
        batch_op.drop_column('niveau_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matieres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('niveau_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('parcours_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('matieres_parcours_id_fkey'), 'parcours', ['parcours_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('matieres_niveau_id_fkey'), 'niveaux', ['niveau_id'], ['id'])

    op.create_table('matiere_enseignant',
    sa.Column('matiere_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('enseignant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date_assignment', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['enseignant_id'], ['enseignant.id'], name=op.f('matiere_enseignant_enseignant_id_fkey')),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], name=op.f('matiere_enseignant_matiere_id_fkey')),
    sa.PrimaryKeyConstraint('matiere_id', 'enseignant_id', name=op.f('matiere_enseignant_pkey'))
    )
    op.drop_table('matiere_enseignant_niveau_parcours')
    # ### end Alembic commands ###
