"""Add matieres table and matiere_enseignant relationship

Revision ID: c33073617548
Revises: 2eb46d62b200
Create Date: 2025-09-18 20:53:26.203571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c33073617548'
down_revision = '2eb46d62b200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matieres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('niveau_id', sa.Integer(), nullable=True),
    sa.Column('parcours_id', sa.Integer(), nullable=True),
    sa.Column('est_actif', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['niveau_id'], ['niveaux.id'], ),
    sa.ForeignKeyConstraint(['parcours_id'], ['parcours.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('matiere_enseignant',
    sa.Column('matiere_id', sa.Integer(), nullable=False),
    sa.Column('enseignant_id', sa.Integer(), nullable=False),
    sa.Column('date_assignment', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['enseignant_id'], ['enseignant.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.PrimaryKeyConstraint('matiere_id', 'enseignant_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matiere_enseignant')
    op.drop_table('matieres')
    # ### end Alembic commands ###
